#!/bin/sh

# osascript - "$1" "$2" <<'APPLESCRIPT'
# on run argv
#   display notification (item 2 of argv) with title (item 1 of argv)
# end run
# APPLESCRIPT

title=$1
message=$2
session_id=$3
window_id=$4
pane_id=$5

execute="$HOME/.config/tmux/tmux-jump '$session_id' '$window_id' '$pane_id'"

exec /opt/homebrew/bin/terminal-notifier \
  -title "$title" \
  -message "$message" \
  -sound Glass \
  -group "tmux-${session_id}-${window_id}" \
  -execute "$execute"
